services:
  modl-env:
    build:
      context: ../third-party-modl
      args:
        IGNITION_VERSION: 8.1.44
    pull_policy: build
    #image: inductiveautomation/ignition:8.1.44
    ports:
      - "8089:8088"
    environment:
      IGNITION_UID: 2003
      IGNITION_GID: 2003
      ACCEPT_IGNITION_EULA: Y
      GATEWAY_ADMIN_USERNAME: ${GATEWAY_USERNAME:-admin}
      GATEWAY_ADMIN_PASSWORD: ${GATEWAY_PASSWORD:-password}
      GATEWAY_MODULES_ENABLED: opc-ua,perspective,siemens-drivers,sql-bridge,web-developer,tag-historian
      DISABLE_QUICKSTART: true
    user: "0:0"
    volumes:
      - ../build/Hmi-Components.unsigned.modl:/usr/local/bin/ignition/user-lib/modules/Hmi-Components.unsigned.modl
      - ./backups/gateway.gwbk:/restore.gwbk
      - ../web:/web-resources
      - ./backups/projects:/usr/local/bin/ignition/data/projects
    labels:
      traefik.enable: "true"
      traefik.hostname: "perspective-component"
    command: >
      -n perspective-modl-dev
      -r /restore.gwbk
      --
      -Dia.developer.moduleupload=true
      -Dignition.allowunsignedmodules=true
      -Dres.path.dev.aflittlejohns.perspective.hmi.Components=/web-resources/build/generated-resources/mounted

    # If a traefik proxy container is not being used, comment out everything below this line (https://github.com/design-group/traefik-proxy)
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
