services:
  gateway:
    image: inductiveautomation/ignition:8.1.44
    ports:
      - "8088:8088"
    environment:
      ACCEPT_IGNITION_EULA: Y
      GATEWAY_ADMIN_USERNAME: ${GATEWAY_USERNAME:-admin}
      GATEWAY_ADMIN_PASSWORD: ${GATEWAY_PASSWORD:-password}
      GATEWAY_MODULES_ENABLED: perspective
      DISABLE_QUICKSTART: true
    volumes:
      - ../build/Hmi-Components.unsigned.modl:/usr/local/bin/ignition/user-lib/modules/Hmi-Components.unsigned.modl
      - ./backups/gateway.gwbk:/restore.gwbk
      - ../web:/web-resources
      - ./backups/project:/usr/local/bin/ignition/data/projects
    labels:
      traefik.enable: "true"
      traefik.hostname: "perspective-component"
    command: >
      -n perspective-component-gateway
      -r /restore.gwbk
      --
      -Dia.developer.moduleupload=true
      -Dignition.allowunsignedmodules=true
      -Dres.path.dev.aflittlejohns.perspective.hmi.Components=/web-resources/build/generated-resources/mounted

    # If a traefik proxy container is not being used, comment out everything below this line (https://github.com/design-group/traefik-proxy)
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
