name: Deploy Docusaurus Documentation

on:
  push:
    branches:
      - main # or master, depending on your default branch
    paths:
      - "docs/**" # Only trigger on changes to docs directory
  workflow_dispatch: # Allow manual triggering

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if last commit merged docs branch
        id: check_merge
        run: |
          # Get the last merge commit message
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $LAST_COMMIT_MSG"
          # Check if it merged 'docs' branch
          if [[ "$LAST_COMMIT_MSG" == *"Merge branch 'docs'"* ]] || [[ "$LAST_COMMIT_MSG" == *"Merge pull request"* && "$LAST_COMMIT_MSG" == *"docs"* ]]; then
            echo "docs_merge=true" >> $GITHUB_OUTPUT
          else
            echo "docs_merge=false" >> $GITHUB_OUTPUT
          fi

      - name: Run only on docs->main merge
        if: steps.check_merge.outputs.docs_merge == 'true'
        run: |
          echo "This job runs only when docs branch was merged into main."

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
